---
language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
sudo: false
before_script:
  - sh -e /etc/init.d/xvfb start
  - export DISPLAY=:99.0
  - bundle exec rake test_app
script:
  - bundle exec rspec spec
